services:
  - type: web
    name: ai-questionnaire-backend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: OPENAI_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://ai-questionnaire-builder.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100